name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip Project
        run: |
          rm -rf app gradle build.gradle.kts settings.gradle.kts
          unzip -o newBilal.zip
          ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle 9.3.1
        run: |
          gradle wrapper --gradle-version 9.3.1
          chmod +x gradlew
          ./gradlew --version

      - name: Build APK
        run: |
          ./gradlew assembleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Bilal-APK-6194905
          path: app/build/outputs/apk/release/*.apk
